/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenewalScheduleRouteImport } from './routes/renewal-schedule'
import { Route as RegistrationFeesRouteImport } from './routes/registration-fees'
import { Route as MemosRouteImport } from './routes/memos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesLtoPlateNumberScheduleExplainedRouteImport } from './routes/guides/lto-plate-number-schedule-explained'
import { Route as GuidesLtoLateRegistrationPenaltyRouteImport } from './routes/guides/lto-late-registration-penalty'
import { Route as GuidesHowToRenewLtoRegistrationRouteImport } from './routes/guides/how-to-renew-lto-registration'

const RenewalScheduleRoute = RenewalScheduleRouteImport.update({
  id: '/renewal-schedule',
  path: '/renewal-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationFeesRoute = RegistrationFeesRouteImport.update({
  id: '/registration-fees',
  path: '/registration-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosRoute = MemosRouteImport.update({
  id: '/memos',
  path: '/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesLtoPlateNumberScheduleExplainedRoute =
  GuidesLtoPlateNumberScheduleExplainedRouteImport.update({
    id: '/guides/lto-plate-number-schedule-explained',
    path: '/guides/lto-plate-number-schedule-explained',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesLtoLateRegistrationPenaltyRoute =
  GuidesLtoLateRegistrationPenaltyRouteImport.update({
    id: '/guides/lto-late-registration-penalty',
    path: '/guides/lto-late-registration-penalty',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHowToRenewLtoRegistrationRoute =
  GuidesHowToRenewLtoRegistrationRouteImport.update({
    id: '/guides/how-to-renew-lto-registration',
    path: '/guides/how-to-renew-lto-registration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/memos': typeof MemosRoute
  '/registration-fees': typeof RegistrationFeesRoute
  '/renewal-schedule': typeof RenewalScheduleRoute
  '/guides/how-to-renew-lto-registration': typeof GuidesHowToRenewLtoRegistrationRoute
  '/guides/lto-late-registration-penalty': typeof GuidesLtoLateRegistrationPenaltyRoute
  '/guides/lto-plate-number-schedule-explained': typeof GuidesLtoPlateNumberScheduleExplainedRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/memos': typeof MemosRoute
  '/registration-fees': typeof RegistrationFeesRoute
  '/renewal-schedule': typeof RenewalScheduleRoute
  '/guides/how-to-renew-lto-registration': typeof GuidesHowToRenewLtoRegistrationRoute
  '/guides/lto-late-registration-penalty': typeof GuidesLtoLateRegistrationPenaltyRoute
  '/guides/lto-plate-number-schedule-explained': typeof GuidesLtoPlateNumberScheduleExplainedRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/memos': typeof MemosRoute
  '/registration-fees': typeof RegistrationFeesRoute
  '/renewal-schedule': typeof RenewalScheduleRoute
  '/guides/how-to-renew-lto-registration': typeof GuidesHowToRenewLtoRegistrationRoute
  '/guides/lto-late-registration-penalty': typeof GuidesLtoLateRegistrationPenaltyRoute
  '/guides/lto-plate-number-schedule-explained': typeof GuidesLtoPlateNumberScheduleExplainedRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/memos'
    | '/registration-fees'
    | '/renewal-schedule'
    | '/guides/how-to-renew-lto-registration'
    | '/guides/lto-late-registration-penalty'
    | '/guides/lto-plate-number-schedule-explained'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/memos'
    | '/registration-fees'
    | '/renewal-schedule'
    | '/guides/how-to-renew-lto-registration'
    | '/guides/lto-late-registration-penalty'
    | '/guides/lto-plate-number-schedule-explained'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/memos'
    | '/registration-fees'
    | '/renewal-schedule'
    | '/guides/how-to-renew-lto-registration'
    | '/guides/lto-late-registration-penalty'
    | '/guides/lto-plate-number-schedule-explained'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  MemosRoute: typeof MemosRoute
  RegistrationFeesRoute: typeof RegistrationFeesRoute
  RenewalScheduleRoute: typeof RenewalScheduleRoute
  GuidesHowToRenewLtoRegistrationRoute: typeof GuidesHowToRenewLtoRegistrationRoute
  GuidesLtoLateRegistrationPenaltyRoute: typeof GuidesLtoLateRegistrationPenaltyRoute
  GuidesLtoPlateNumberScheduleExplainedRoute: typeof GuidesLtoPlateNumberScheduleExplainedRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renewal-schedule': {
      id: '/renewal-schedule'
      path: '/renewal-schedule'
      fullPath: '/renewal-schedule'
      preLoaderRoute: typeof RenewalScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-fees': {
      id: '/registration-fees'
      path: '/registration-fees'
      fullPath: '/registration-fees'
      preLoaderRoute: typeof RegistrationFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos': {
      id: '/memos'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/lto-plate-number-schedule-explained': {
      id: '/guides/lto-plate-number-schedule-explained'
      path: '/guides/lto-plate-number-schedule-explained'
      fullPath: '/guides/lto-plate-number-schedule-explained'
      preLoaderRoute: typeof GuidesLtoPlateNumberScheduleExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/lto-late-registration-penalty': {
      id: '/guides/lto-late-registration-penalty'
      path: '/guides/lto-late-registration-penalty'
      fullPath: '/guides/lto-late-registration-penalty'
      preLoaderRoute: typeof GuidesLtoLateRegistrationPenaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-renew-lto-registration': {
      id: '/guides/how-to-renew-lto-registration'
      path: '/guides/how-to-renew-lto-registration'
      fullPath: '/guides/how-to-renew-lto-registration'
      preLoaderRoute: typeof GuidesHowToRenewLtoRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  MemosRoute: MemosRoute,
  RegistrationFeesRoute: RegistrationFeesRoute,
  RenewalScheduleRoute: RenewalScheduleRoute,
  GuidesHowToRenewLtoRegistrationRoute: GuidesHowToRenewLtoRegistrationRoute,
  GuidesLtoLateRegistrationPenaltyRoute: GuidesLtoLateRegistrationPenaltyRoute,
  GuidesLtoPlateNumberScheduleExplainedRoute:
    GuidesLtoPlateNumberScheduleExplainedRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
